version: '3.8'
services:
  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: abcd1234
      MYSQL_DATABASE: db_web_portal
      MYSQL_USER: root
      MYSQL_PASSWORD: abcd1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springmysql

  spring-app:
    build:
      context: . # Pretpostavljam da ti je Dockerfile u rootu projekta
      dockerfile: Dockerfile
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/db_web_portal?autoReconnect=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: abcd1234
    depends_on:
      - mysql-db
    networks:
      - springmysql

networks:
  springmysql:
    driver: bridge

volumes:
  mysql_data: